"""
File Name: flatscan_parameters.py
Description: FLATSCAN Parameters
© Carnegie Mellon University - MSE - Sensolution
"""

ACK_TIMEOUT_TIME = 1

# Parameters for SYNC field
# sync pattern: 0xbea01234
SYNC_PATTERN = b'\xbe\xa0\x12\x34'
SYNC_PROTOCOL = b'\x02'
SYNC_VERIFICATION = b'\x02'
SYNC_FUTURE = b'\x00\x00\x00'
SYNC_MSG_LEN_BYTES = 2
SYNC_MSG_LEN_OFFSET = 5

# Parameters for SET_LED
# SET_LED cmd: 0xc378
SET_LED_CMD = b'\x78\xc3'
SET_LED_LEN = 19
LED_ACTIONS = {'set': b'\x01', 'blink': b'\x02'}
LED_COLORS = {'off': b'\x00', 'red': b'\x01', 'green': b'\x02', 'orange': b'\x03'}
LED_FREQ_RANGE = range(1, 10)

# Parameters for GET_MEASUREMENTS
#GET_MEASUREMENTS cmd: 0xc35b
GET_MEASUREMENTS_CMD = b'\x5b\xc3'
GET_MEASUREMENTS_LEN = 16

# Parameters for GET_PARAMETERS
# GET_PARAMETERS cmd: 0xc354
GET_PARAMETERS_CMD = b'\x54\xc3'
GET_PARAMETERS_LEN = 15

# Parameters for GET_EMERGENCY
# GET_EMERGENCY cmd: 0xc36e
GET_EMERGENCY_CMD = b'\x6e\xc3'
GET_EMERGENCY_LEN = 15

# Parameters for SET_PARAMETERS
# SET_PARAMETERS cmd: 0xc353
SET_PARAMETERS_CMD = b'\x53\xc3'
SET_PARAMETERS_LEN = 37

# Parameters for GET_IDENTITY
# GET_IDENTITY cmd: 0xc35a
GET_IDENTITY_CMD = b'\x5a\xc3'
GET_IDENTITY_LEN = 15

# Parameters for RESET_MDI_COUNTER
RESET_MDI_COUNTER_CMD = b'\x5e\xc3'
RESET_MDI_COUNTER_LEN = 15

# Parameters for RESET_HEARTBEAT_COUNTER
RESET_HEARTBEAT_COUNTER_CMD = b'\x5f\xc3'
RESET_HEARTBEAT_COUNTER_LEN = 15

# Parameters for RESET_EMERGENCY_COUNTER
RESET_EMERGENCY_COUNTER_CMD = b'\x61\xc3'
RESET_EMERGENCY_COUNTER_LEN = 15

# Parameters for SET_BAUDRATE
SET_BAUDRATE_CMD = b'\x51\xc3'
SET_BAUDRATE_LEN = 16

# Parameters for messages
# 11 bytes SYNC + 2 bytes CMD + 2 bytes CHK
MINIMAL_MSG_LEN = 15
SYNC_FIELD_LEN = 11
SYNC_PATTERN_LEN = 4
CMD_FIELD_OFFSET = 11
CMD_FIELD_LEN = 2
CHK_FIELD_LEN = 2
DATA_FIELD_OFFSET = 13

# Parameters for messages CMD
# MDI frame CMD: 50011(0xc35b)
MSG_MDI_CMD = b'\x5b\xc3'
# SEND_IDENTITY frame CMD: 50010(0xc35a)
MSG_SEND_IDENTITY_CMD = b'\x5a\xc3'
# SEND_PARAMETERS frame CMD: 50004(0xc354)
MSG_SEND_PARAMETERS_CMD = b'\x54\xc3'
# HEARTBEAT frame CMD: 50020(0xc364)
MSG_HEARTBEAT_CMD = b'\x64\xc3'
# EMERGENCY frame CMD: 50030(0xc36e)
MSG_EMERGENCY_CMD = b'\x6e\xc3'
MSG_VALID_CMD_SET = {MSG_MDI_CMD, MSG_SEND_PARAMETERS_CMD, MSG_SEND_IDENTITY_CMD, MSG_HEARTBEAT_CMD, MSG_EMERGENCY_CMD}

# Parameters for ACK
ACK_SET_BAUDRATE = b'\x51\xc3'
ACK_STORE_PARAMETERS = b'\x55\xc3'
ACK_RESET_MDI_COUNTER = b'\x5e\xc3'
ACK_RESET_HEARTBEAT_COUNTER = b'\x5f\xc3'
ACK_RESET_EMERGENCY_COUNTER = b'\x61\xc3'
ACK_SET_LED = b'\x78\xc3'
ACK_CMD_SET = {ACK_SET_BAUDRATE, ACK_STORE_PARAMETERS, ACK_RESET_MDI_COUNTER, ACK_RESET_HEARTBEAT_COUNTER,
               ACK_RESET_EMERGENCY_COUNTER, ACK_SET_LED}

# Parameters for HEARTBEAT messages
HEARTBEAT_MSG_LENS = {15, 21}
HEARTBEAT_CAN_LEN = 4
HEARTBEAT_CNTR_LEN = 2

# Parameters for SEND_PARAMETERS messages
PARAMETERS_MSG_LEN = 43
PARAMETERS_VERIFICATION_BITS_LEN = 4
PARAMETERS_TEMPERATURE_OFFSET = 7
PARAMETERS_MDI_INFO_OFFSET = 8
PARAMETERS_DETECTION_FIELD_MODE_OFFSET = 9
PARAMETERS_SENSITIVITY_OFFSET = 10
PARAMETERS_NUM_SPOTS_OFFSET = 14
PARAMETERS_NUM_SPOTS_LEN = 2
PARAMETERS_ANGLE_FIRST_OFFSET = 20
PARAMETERS_ANGLE_FIRST_LEN = 2
PARAMETERS_ANGLE_LAST_OFFSET = 22
PARAMETERS_ANGLE_LAST_LEN = 2
PARAMETERS_CAN_AND_FRAME_COUNTER_OFFSET = 24
PARAMETERS_HEARTBEAT_PERIOD_OFFSET = 25
PARAMETERS_FACET_NUMBER_FIELD_OFFSET = 26
PARAMETERS_AVERAGING_OFFSET = 27

# Parameters for SEND_IDENTITY messages
IDENTITY_MSG_LEN = 27
IDENTITY_PRODUCT_PART_NUMBER_LEN = 4
IDENTITY_SOFTWARE_VERSION_OFFSET = 4
IDENTITY_SOFTWARE_REVISION_OFFSET = 5
IDENTITY_SOFTWARE_PROTOTYPE_OFFSET = 6
IDENTITY_CAN_NUMBER_OFFSET = 7
IDENTITY_CAN_NUMBER_LEN = 4

# Parameters for EMERGENCY messages
EMERGENCY_MSG_LENS = {19, 25}
EMERGENCY_DATA_WITH_CAN_CNTR_LEN = 10
EMERGENCY_CAN_LEN = 4
EMERGENCY_CNTR_OFFSET = 4
EMERGENCY_CNTR_LEN = 2
EMERGENCY_RS485_OFFSET = 6
EMERGENCY_RS485_LEN = 2
EMERGENCY_MEASURING_HEAD_OFFSET = 8
EMERGENCY_MEASURING_HEAD_LEN = 2

# Parameters for MDI messages
MDI_CAN_LEN = 4
MDI_CNTR_LEN = 2
MDI_CTN_LEN = 2
MDI_FACET_LEN = 1
MDI_MEASUREMENT_LEN = 2

# Parameters for Serial Communication
FLATSCAN_TIMEOUT = 10
BAUDRATE_DEFAULT = 921600
BAUDRATE_AVAILABLE = [57600, 115200, 230400, 460800, 921600]

# Parameters for verification_bits
VERIFICATION_BIT_TEMPERATURE = 1
VERIFICATION_BIT_MDI_INFO = 2
VERIFICATION_BIT_DETECTION_FIELD_MODE = 3
VERIFICATION_BIT_SENSITIVITY = 4
VERIFICATION_BIT_NUM_SPOTS = 9
VERIFICATION_BIT_ANGLE_FIRST = 12
VERIFICATION_BIT_ANGLE_LAST = 13
VERIFICATION_BIT_CAN_AND_FRAME_COUNTER = 14
VERIFICATION_BIT_HEARTBEAT_PERIOD = 15
VERIFICATION_BIT_FACET_NUMBER_FIELD = 16
VERIFICATION_BIT_AVERAGING = 17

# rs485 error messages code
RS485_INTEGRITY_FAIL1 = b'\x01\x80'
RS485_INTEGRITY_FAIL2 = b'\xaa\x80'
RS485_HARDWARE_FAIL = b'\x0d\x50'
RS485_INPUT_SUPPLY = b'\x0a\x50'
RS485_NO_ERROR = b'\x00\x00'

# measure head messages code
MEASURE_HEAD_INTEGRITY_FAIL1 = b'\x01\x80'
MEASURE_HEAD_INTEGRITY_FAIL2 = b'\xaa\x80'
MEASURE_HEAD_HARDWARE_FAIL1 = b'\x01\x50'
MEASURE_HEAD_HARDWARE_FAIL2 = b'\x20\x50'
MEASURE_HEAD_COMMUNICATION_ERROR1 = b'\x01\x81'
MEASURE_HEAD_COMMUNICATION_ERROR2 = b'\x04\x81'
MEASURE_HEAD_NO_ERROR = b'\x00\x00'
